[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "18"

# API redirects to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://video-cutter-rj1z.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/files/*"
  to = "https://video-cutter-rj1z.onrender.com/files/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
